title: "Hari's Blog"
description: " I am writing here - hari"
baseurl: ""   # leave empty for user.github.io/repo
url: ""       # will be set by GitHub Pages
markdown: kramdown
theme: null   # disable default theme since we use custom layout
author:
  name: "Harisankar SH"
  email: "har.i@icloud.com"
